### PR TITLE
ReFaCtOr ThInGz, fix #23, fix #22, fix #8, fix #15, fix #14

### LINKED ISSUE #8: Enums missing 'type' property
I've been using this library to convert my Sequelize models into JSON schemas for generating swagger definitions and I've found an issue where swagger requires `type` to be defined on enums as so:

```{
  ...
  "properties": {
    "myEnum": {
      "type": "string",
      "enum": ["ONE", "TWO", "THREE"]
    }
  }
```

I can't come to a good conclusion whether this is part of the JSON schema spec or not, but most research I've done leads me to believe `type` is an attribute worth having.

I was having a think whether enums can be any other type, and I don't think they can (or that you would want it?)

Happy to make a PR, or all that needs doing is adding the following line in `src/index.js:8`

```
 5: let enumProperty = attribute => {
 6:    return {
 7:      enum: attribute.values,
 8:      type: 'string'
 9:    }
10: }
```

### LINKED ISSUE #14: any plans to support relations ?

### LINKED ISSUE #15: Add support for types ARRAY and VIRTUAL of arrays
Add support to allow use of VIRTUAL with ARRAY and support for ARRAY generally.

### LINKED ISSUE #22: Is this repo abandoned?
No activity and PRs open for almost a year, should we avoid using this repository?

@chaliy if so, perhaps archive it to make it more clear for future visitors. https://github.blog/2017-11-08-archiving-repositories/

### LINKED ISSUE #23: 'any' is not a valid type
JSON and JSONB attributes currently map to JSON-Schema properties of type `"any"`, which is not a valid type.  This causes AJV to throw errors like this:
> data.properties['some_property'].type should be equal to one of the allowed values

JSON types should map to `{type: ['array', 'object', 'string', 'number', 'boolean', 'null']}`

### PR DESCRIPTION
**Pull request by broofa**
Pretty much a wholesale rewrite.  Update dependencies to fix
npm audit warnings, remove unnecessary packages, fix some issues.  ES6-ify the code... and whatever else happened to fall into my evil clutches while I was playing around in this.  Sorry!

[Other readers: I've emailed @chaliy to see about maintaining this module.]

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Good job, fingers crossed for reviving.

**Comment by chaliy** [comment]
LGTM, can release this as 2.0.0 version

**Comment by broofa** [comment]
@chaliy @bravo-kernel

Since this is going to be a major release, I've opted to make a few changes to the API that (I hope) you'll agree make sense.  In summary:

* Export the main function as ~~`exports.getJSONSchema`~~ [Edit: now `exports.getModelSchema`] instead of as default export .  This will allow for more flexibility in the API moving forward (e.g. adding the `allowNullType()` function, below).
* ~~Rename `attributes` option to `include`, to be consistent with Sequelize and to mirror the `exclude` option~~ [Edit: reverted this change after realizing the sequelize option is actually `attributes`]
* Remove `alwaysRequired` option.  I don't see this as having much value.  1. Required/optional is typically a per-attribute decision and 2. It's easy for users to do manually if they really want this. (e.g. `schema.required.push(...Object.keys(schema.properties))`)
* Remove `allowNull` option.  Having this set as a model-level option was confusing.  E.g. What if `options.allowNull===false`, but `attribute.allowNull===true`?  Instead, this mimics sequelize behavior ('null' is allowed unless allowNull explicitly set to `false`).
* Stricter options checks (to catch errors earlier).
* ~~... for users that want to tweak whether null is/isn't allowed , export the `allowNullType` helper function~~  [Edit: removed this from API for the time being, as it just doesn't feel quite right.]

Let me know what you think.  Unless there are change requests, I vote we push this out as v2.0.  (@chaliy do you want to take care of that?  If not, I'm happy to do that - I'll need collaborator perms here, and owner perms on npm for that however.)

**Comment by broofa** [comment]
Added support for describing associations, which led to breaking the API up into the three methods (described in the [README](https://github.com/broofa/sequelize-json-schema/blob/refactor/README.md)).

[Side note: The README is now run through my runmd module.   'I know it's a little kludgy, but it insures the code examples are runnable, and that the code output is consistent with the code shown.  I hope that's okay.]

**Comment by broofa** [comment]
@chaliy I'm done fiddling with this.  Can you review/merge/publish?

**Comment by bravo-kernel** [comment]
@broofa since you are interested in this topic as well I would like to point you to a possible alternative. I have taken your PR (and various similar repositories) as inspiration to fill the sequelize-to-xxx gap with a solution that uses the strategy-pattern. This way, it will be possible to re-use (rock solid) core functionality while easily adding support for new schema variants and versions. 

https://github.com/alt3/sequelize-to-json-schemas

**Comment by chaliy** [comment]
@broofa  , changes looks good for me. If you care to add section on migration to v2.0.0; author in package.json, I am good to go. You have all permissions you need to proceed with release.

**Comment by broofa** [comment]
My apologies for taking so long to act on this.  I've been swamped with work and life in general, but finally got a few hours to focus on this.

I've merged this PR to master (obviously) and npm published as v2.0.0.   This is after a handful of commits to clean up files, config, docs, and whatnot.  Hopefully nothing too controversial in there.

@chaliy:  I tagged the prior release as v1.3.0, in case anyone needs to get back to that.  (I verified that master HEAD was identical with the 1.3.0 npm release).  Please let me know if I overstepped or went astray with any of this.

@bravo-kernel:  My apologies for not addressing the work you've done on your fork.  I glanced at it and I like the basic idea of supporting different schema formats but I only have a few hours right now and wanted to see if I could wrap this PR up in it's current form.  Let's keep the conversation going, though.

**Comment by bravo-kernel** [comment]
Appreciate your mention and... no apologize needed, everything is already done and has worked out fine.  Good job on this PR. Enjoy the new year 👍

**Pull request merged**
